-- forecast_run: registry of forecasting-pipeline runs. One row per run
-- (status, model/version, timings, per-segment summary). Root key
-- forecast_run_id, to which the points and quality metrics below are tied.
CREATE TABLE IF NOT EXISTS forecast_run (
    forecast_run_id String,
    forecast_job    String,
    status          String,
    model_name      String,
    model_version   String,
    started_at      DateTime,
    finished_at     Nullable(DateTime),
    segments_total  UInt32,
    segments_skipped UInt32,
    error           Nullable(String),
    created_at      DateTime DEFAULT now()
) ENGINE = MergeTree
PARTITION BY toYYYYMM(created_at)
ORDER BY (forecast_run_id, started_at)
{RETENTION_MONTHS_TTL};

-- forecast_point: the forecast values themselves — one point per (metric,
-- segment, horizon step). Stores the central estimate y_hat, the percentiles
-- p10/p50/p90 and the actual value y_actual (filled in later for quality scoring).
CREATE TABLE IF NOT EXISTS forecast_point (
    forecast_run_id String,
    metric_name     String,
    segment_key     String,
    forecast_ts     DateTime,
    horizon_step    UInt16,
    y_hat           Float64,
    p10             Float64,
    p50             Float64,
    p90             Float64,
    y_actual        Nullable(Float64),
    model_name      String,
    created_at      DateTime DEFAULT now()
) ENGINE = MergeTree
PARTITION BY toYYYYMM(created_at)
ORDER BY (metric_name, segment_key, forecast_ts)
{RETENTION_MONTHS_TTL};

-- forecast_segment: aggregated forecast quality for each segment within a
-- run — error metrics (wape, mape, bias), interval coverage (coverage),
-- series size (n_points) and a sparsity flag (is_sparse).
CREATE TABLE IF NOT EXISTS forecast_segment (
    forecast_run_id String,
    metric_name     String,
    segment_key     String,
    n_points        UInt32,
    is_sparse       UInt8,
    wape            Float64,
    mape            Float64,
    coverage        Float64,
    bias            Float64,
    created_at      DateTime DEFAULT now()
) ENGINE = MergeTree
PARTITION BY toYYYYMM(created_at)
ORDER BY (metric_name, segment_key, forecast_run_id)
{RETENTION_MONTHS_TTL};

-- metric_dependency: detected links between a metric's segments — the output
-- of the dependency-analysis pipeline. A row describes a directed link
-- source -> target with its lag, method, strength (score), direction and
-- significance statistics (p_value, confidence) over a given time window.
CREATE TABLE IF NOT EXISTS metric_dependency (
    analysis_run_id String,
    metric_name     String,
    source_segment  String,
    target_segment  String,
    method          String,
    lag             Int16,
    score           Float64,
    direction       String,
    p_value         Nullable(Float64),
    confidence      Float64,
    window_start    DateTime,
    window_end      DateTime,
    created_at      DateTime DEFAULT now()
) ENGINE = MergeTree
PARTITION BY toYYYYMM(created_at)
ORDER BY (metric_name, target_segment, source_segment, created_at)
{RETENTION_MONTHS_TTL};

-- dependency_explanation: interpretation of the links from metric_dependency,
-- generated by an LLM. Stores a verdict on whether the link is real (is_real),
-- a textual explanation, caveats and a change note (change_note), along with
-- the model used (llm_model).
CREATE TABLE IF NOT EXISTS dependency_explanation (
    analysis_run_id String,
    metric_name     String,
    source_segment  String,
    target_segment  String,
    lag             Int16,
    direction       String,
    is_real         UInt8,
    confidence      Float64,
    explanation     String,
    caveats         String,
    change_note     String,
    llm_model       String,
    created_at      DateTime DEFAULT now()
) ENGINE = MergeTree
PARTITION BY toYYYYMM(created_at)
ORDER BY (metric_name, target_segment, source_segment, created_at)
{RETENTION_MONTHS_TTL};
