#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Headless Lightdash bootstrap.
#
# Replaces the two manual UI forms (Warehouse connection + dbt connection) with
# API calls + a CLI deploy, so a fresh local stack comes up fully configured:
#
#   1. wait for the server          GET  /api/v1/health   (results.needsSetup)
#   2. register the first admin     POST /api/v1/user
#   3. name the organization        PATCH /api/v1/user/me/complete
#   4. mint a personal access token POST /api/v1/user/me/personal-access-tokens
#   5. materialize the models       dbt run
#   6. create the Lightdash project lightdash deploy --create
#
# Step 6 reads the dbt profiles.yml and pushes the warehouse connection
# (ClickHouse) + a compiled manifest, so no warehouse/dbt form is ever filled
# by hand. dbt connection type is "cli/none" (managed via deploy, no git).
#
# Idempotent: re-running skips registration if the instance is already set up
# and re-deploys instead of re-creating.
# ---------------------------------------------------------------------------
set -euo pipefail

LIGHTDASH_URL="${LIGHTDASH_URL:-http://lightdash:8080}"
DBT_DIR="${DBT_PROJECT_DIR:-/usr/app/dbt}"
COOKIE_JAR="$(mktemp)"
trap 'rm -f "$COOKIE_JAR"' EXIT

req() { curl -fsS -b "$COOKIE_JAR" -c "$COOKIE_JAR" -H 'Content-Type: application/json' "$@"; }

echo "==> Waiting for Lightdash at ${LIGHTDASH_URL} ..."
healthy=""
for _ in $(seq 1 60); do
  if curl -fsS "${LIGHTDASH_URL}/api/v1/health" >/dev/null 2>&1; then
    healthy=1; echo "    up"; break
  fi
  sleep 3
done
[ -n "$healthy" ] || { echo "ERROR: Lightdash never became healthy"; exit 1; }

# Try to register the first admin. On a fresh instance this succeeds and the
# user becomes org owner; if a user already exists the API 4xxs and we log in
# instead. (The health payload has no reliable "needsSetup" flag across
# versions, so we drive off the register result.)
echo "==> Registering admin ${LD_ADMIN_EMAIL}"
if req -X POST "${LIGHTDASH_URL}/api/v1/user" -d "$(jq -n \
      --arg f "$LD_ADMIN_FIRST_NAME" --arg l "$LD_ADMIN_LAST_NAME" \
      --arg e "$LD_ADMIN_EMAIL"      --arg p "$LD_ADMIN_PASSWORD" \
      '{firstName:$f, lastName:$l, email:$e, password:$p}')" >/dev/null 2>&1; then
  echo "==> Naming organization '${LD_ORG_NAME}'"
  req -X PATCH "${LIGHTDASH_URL}/api/v1/user/me/complete" -d "$(jq -n \
    --arg o "$LD_ORG_NAME" \
    '{organizationName:$o, jobTitle:"engineer", isMarketingOptedIn:false, isTrackingAnonymized:true, enableEmailDomainAccess:false}')" \
    >/dev/null || echo "    (complete-setup returned non-2xx; continuing)"
else
  echo "==> Registration rejected (already set up?) — logging in"
  req -X POST "${LIGHTDASH_URL}/api/v1/login" -d "$(jq -n \
    --arg e "$LD_ADMIN_EMAIL" --arg p "$LD_ADMIN_PASSWORD" \
    '{email:$e, password:$p}')" >/dev/null
fi

echo "==> Minting personal access token"
pat="$(req -X POST "${LIGHTDASH_URL}/api/v1/user/me/personal-access-tokens" -d \
  '{"expiresAt":null,"description":"norn-bootstrap","autoGenerated":false}' \
  | jq -r '.results.token')"
[ -n "$pat" ] && [ "$pat" != "null" ] || { echo "ERROR: failed to mint PAT"; exit 1; }

export LIGHTDASH_API_KEY="$pat"
export LIGHTDASH_URL
export CI=true
export DBT_PROFILES_DIR="$DBT_DIR"

echo "==> dbt run ($DBT_DIR)"
cd "$DBT_DIR"
dbt run --project-dir . --profiles-dir .

echo "==> Publishing project '${LD_PROJECT_NAME}' to Lightdash"
if [ -f ".lightdash.yml" ] || [ -f "lightdash.config.yml" ]; then
  lightdash deploy --project-dir . --profiles-dir .
else
  lightdash deploy --create "$LD_PROJECT_NAME" --project-dir . --profiles-dir . \
    || lightdash deploy --project-dir . --profiles-dir .
fi

echo "==> Done. Open ${SITE_URL:-$LIGHTDASH_URL} and log in as ${LD_ADMIN_EMAIL}"
